/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package log_analyzer

import spock.lang.Specification
import spock.util.environment.RestoreSystemProperties

import java.nio.file.Paths

@RestoreSystemProperties
class LogAnalyzerSpec extends Specification {

    def "Should validate a file is splitted by days"() {
        setup: "Creating a file"
        File tmpDir = File.createTempDir()
        File tmpTargetDir = File.createTempDir()
        File tmpFile = new File(Paths.get(tmpDir.path, "${System.currentTimeMillis().toString()}.log").toString())
        tmpFile.createNewFile()
        tmpFile.append("2020-03-24T21:14:14.367, Server4, This is an awesome log 193\n")
        tmpFile.append("2020-03-18T21:14:14.389, Server4, This is an awesome log 125\n")

        System.setProperty('ORIGIN_PATH', tmpDir.path)
        System.setProperty('SPLIT_STRATEGY', 'DAYS')
        System.setProperty('TARGET_LOGS_PATH', tmpTargetDir.path)

        when: "File is read"
        LogAnalyzer.splitLogFiles()

        then: "Two files appear"
        tmpTargetDir.listFiles().findAll { it.isFile() }.size() == 2

        cleanup: "Remove tmp dirs"
        //println "Cleaning up"
        tmpDir.deleteOnExit()
        tmpTargetDir.deleteOnExit()
        System.clearProperty('TARGET_LOGS_PATH')
        System.clearProperty('ORIGIN_PATH')
        System.clearProperty('SPLIT_STRATEGY')
    }

    def "Should validate a file is ordered and condensed"() {
        setup: "Creating a file"
        File tmpTargetDir = File.createTempDir("${System.currentTimeMillis()}", "${System.currentTimeMillis()}")
        File tmpFile1 = new File(Paths.get(tmpTargetDir.path, "2020_03_19").toString())
        tmpFile1.createNewFile()
        tmpFile1.append("""
2020-03-19T21:14:14.389, Server4, This is an awesome log 125
2020-03-19T20:14:14.389, Server3, This is an awesome log 125
""")


        File tmpFile2 = new File(Paths.get(tmpTargetDir.path, "2020_03_20").toString())
        tmpFile2.createNewFile()
        tmpFile2.append("""
2020-03-19T21:14:14.389, Server4, This is an awesome log 125
2020-03-19T20:14:14.389, Server3, This is an awesome log 125
""")

        System.setProperty('TARGET_LOGS_PATH', tmpTargetDir.path)
        System.setProperty('SPLIT_STRATEGY', 'DAYS')

        when: "Files are merged"
        LogAnalyzer.mergeFiles()

        then: "Condensed log is ordered"

        List<String> condensedContent = tmpTargetDir
                .listFiles()
                //.each {println it.name}
                .findAll { it.isFile() && it.name =~ LogAnalyzer.TARGET_LOG_NAME }.first().readLines()
        List<String> expectedContent = [
                "2020-03-19T20:14:14.389, Server3, This is an awesome log 125",
                "2020-03-19T21:14:14.389, Server4, This is an awesome log 125",
                "2020-03-20T20:14:14.389, Server3, This is an awesome log 125",
                "2020-03-20T21:14:14.389, Server4, This is an awesome log 125"
        ]
        condensedContent == expectedContent


        cleanup: "Remove tmp dirs"
        //println "Cleaning up"
        tmpTargetDir.deleteDir()
        System.clearProperty('TARGET_LOGS_PATH')
        System.clearProperty('SPLIT_STRATEGY')
    }
}
